<?php
require_once '../config/config.php';
require_once '../includes/paystack_fees.php';

requireLogin();

header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['status' => 'error', 'message' => 'Method not allowed']);
    exit();
}

$payload = json_decode(file_get_contents('php://input'), true);
if (!is_array($payload)) {
    $payload = $_POST;
}

$csrf = $_SERVER['HTTP_X_CSRF_TOKEN'] ?? ($payload['csrf_token'] ?? '');
if (!validateCSRF($csrf)) {
    http_response_code(419);
    echo json_encode(['status' => 'error', 'message' => 'Invalid CSRF token']);
    exit();
}

$reference = sanitize($payload['reference'] ?? '');
if ($reference === '') {
    http_response_code(400);
    echo json_encode(['status' => 'error', 'message' => 'Missing Paystack reference']);
    exit();
}

if (!preg_match('/^PAY_/i', $reference)) {
    http_response_code(400);
    echo json_encode(['status' => 'error', 'message' => 'Only Paystack references generated by this system can be verified here.']);
    exit();
}

$current_user = getCurrentUser();
if (!$current_user) {
    http_response_code(401);
    echo json_encode(['status' => 'error', 'message' => 'Unauthorized']);
    exit();
}

$stmt = $db->prepare("
    SELECT id, user_id, status, transaction_type, payment_method, amount
    FROM transactions
    WHERE reference = ?
    LIMIT 1
");
$stmt->bind_param('s', $reference);
$stmt->execute();
$transaction = $stmt->get_result()->fetch_assoc();
$stmt->close();

if (!$transaction) {
    http_response_code(404);
    echo json_encode(['status' => 'error', 'message' => 'Transaction not found']);
    exit();
}

if ((int) $transaction['user_id'] !== (int) $current_user['id']) {
    http_response_code(403);
    echo json_encode(['status' => 'error', 'message' => 'Forbidden']);
    exit();
}

if (($transaction['payment_method'] ?? '') !== 'paystack' || ($transaction['transaction_type'] ?? '') !== 'topup') {
    http_response_code(400);
    echo json_encode(['status' => 'error', 'message' => 'Only pending Paystack wallet top-ups can be verified here.']);
    exit();
}

$transaction_status = strtolower(trim((string) ($transaction['status'] ?? '')));
$user_role = strtolower(trim((string) ($current_user['role'] ?? 'customer')));
$wallet_redirect = $user_role === 'agent' ? '/agent/wallet.php' : '/customer/wallet.php';

if ($transaction_status === 'success') {
    echo json_encode([
        'status' => 'success',
        'transaction_status' => 'success',
        'message' => 'Payment was already processed.',
        'redirect_path' => $wallet_redirect,
    ]);
    exit();
}

if ($transaction_status === 'failed') {
    echo json_encode([
        'status' => 'success',
        'transaction_status' => 'failed',
        'message' => 'This payment was previously marked as unsuccessful.',
    ]);
    exit();
}

if ($transaction_status !== 'pending') {
    echo json_encode([
        'status' => 'success',
        'transaction_status' => $transaction_status !== '' ? $transaction_status : 'unknown',
        'message' => 'This transaction is not in a verifiable state.',
    ]);
    exit();
}

$paystack_secret_key = trim((string) dbh_env('PAYSTACK_SECRET_KEY', PAYSTACK_SECRET_KEY));
if ($paystack_secret_key === '') {
    http_response_code(500);
    echo json_encode(['status' => 'error', 'message' => 'Paystack is not configured.']);
    exit();
}

$curl = curl_init();
curl_setopt_array($curl, [
    CURLOPT_URL => 'https://api.paystack.co/transaction/verify/' . rawurlencode($reference),
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_CONNECTTIMEOUT => 15,
    CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'GET',
    CURLOPT_HTTPHEADER => [
        'Authorization: Bearer ' . $paystack_secret_key,
        'Cache-Control: no-cache',
    ],
]);

$response = curl_exec($curl);
$curl_error = curl_error($curl);
$http_code = (int) curl_getinfo($curl, CURLINFO_HTTP_CODE);
curl_close($curl);

if ($curl_error !== '') {
    http_response_code(502);
    echo json_encode(['status' => 'error', 'message' => 'Unable to reach Paystack right now.']);
    exit();
}

$paystack_result = json_decode($response, true);
if (!$paystack_result || !($paystack_result['status'] ?? false) || empty($paystack_result['data'])) {
    http_response_code($http_code >= 400 ? $http_code : 502);
    echo json_encode(['status' => 'error', 'message' => 'Paystack could not verify this reference right now.']);
    exit();
}

$gateway_data = $paystack_result['data'];
$gateway_status = strtolower(trim((string) ($gateway_data['status'] ?? '')));
$gateway_reference = trim((string) ($gateway_data['reference'] ?? ''));
$gateway_amount = round(((float) ($gateway_data['amount'] ?? 0)) / 100, 2);
$expected_amount = round((float) ($transaction['amount'] ?? 0), 2);

if ($gateway_reference === '' || strcasecmp($gateway_reference, $reference) !== 0) {
    http_response_code(409);
    echo json_encode(['status' => 'error', 'message' => 'Paystack returned a mismatched reference.']);
    exit();
}

if (function_exists('validatePaystackAmount')) {
    $validation = validatePaystackAmount($gateway_amount, $expected_amount);
    if (empty($validation['is_valid'])) {
        http_response_code(409);
        echo json_encode([
            'status' => 'error',
            'message' => 'Amount mismatch detected for this Paystack payment.',
        ]);
        exit();
    }
} elseif (abs($gateway_amount - $expected_amount) > 0.01) {
    http_response_code(409);
    echo json_encode(['status' => 'error', 'message' => 'Amount mismatch detected for this Paystack payment.']);
    exit();
}

if ($gateway_status === 'success') {
    echo json_encode([
        'status' => 'success',
        'transaction_status' => 'success',
        'message' => 'Payment verified. Redirecting to complete wallet credit.',
        'next_url' => SITE_URL . '/api/paystack_callback.php?reference=' . urlencode($reference),
    ]);
    exit();
}

if (in_array($gateway_status, ['failed', 'abandoned', 'reversed'], true)) {
    echo json_encode([
        'status' => 'success',
        'transaction_status' => 'failed',
        'message' => 'Paystack reported this transaction as unsuccessful.',
        'next_url' => SITE_URL . '/api/paystack_callback.php?reference=' . urlencode($reference),
    ]);
    exit();
}

echo json_encode([
    'status' => 'success',
    'transaction_status' => 'pending',
    'message' => 'This payment is still pending on Paystack.',
]);
